// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVk_XSc6VfgZIdnPahvSKe8Jl4JnV8Ns',
    appId: '1:321671261591:web:89c37181da5b90fca0e8d2',
    messagingSenderId: '321671261591',
    projectId: 'login-signin-c6f29',
    authDomain: 'login-signin-c6f29.firebaseapp.com',
    storageBucket: 'login-signin-c6f29.appspot.com',
    measurementId: 'G-4S06HRJ9ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Kjditt_1f4oL0uVl8iU2tRWbSFd7gZU',
    appId: '1:321671261591:android:609671fee44e7d9da0e8d2',
    messagingSenderId: '321671261591',
    projectId: 'login-signin-c6f29',
    storageBucket: 'login-signin-c6f29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCFV_1ampArFmj-aKNIc9MLvehjqKhDw',
    appId: '1:321671261591:ios:75365cb6875cc97aa0e8d2',
    messagingSenderId: '321671261591',
    projectId: 'login-signin-c6f29',
    storageBucket: 'login-signin-c6f29.appspot.com',
    iosBundleId: 'com.example.loginSiginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaCFV_1ampArFmj-aKNIc9MLvehjqKhDw',
    appId: '1:321671261591:ios:4343b9b715206e1aa0e8d2',
    messagingSenderId: '321671261591',
    projectId: 'login-signin-c6f29',
    storageBucket: 'login-signin-c6f29.appspot.com',
    iosBundleId: 'com.example.loginSiginFirebase.RunnerTests',
  );
}
